### GENERAL SETTINGS ###

# Site settings
title: Topor
tagline: "We axe the questions"
analytics: # Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" # important: start with /
url: "http://topor.io"

# Build settings
markdown: kramdown
markdown_ext: "markdown,md"
kramdown:
  syntax_highlighter: rouge
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title
excerpt_separator: <!--more--> # use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

exclude: [README.md, LICENSE, CNAME]

colors:  # in hex code if not noted else
  primary: "#607D8B"
  primary_rgb: "96,125,139" # rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#263238"
  highlight: "#2e3b42"
  link: "#336899"
  link_hover: "#538ec6"
  footer_heading: "#f5f5f5"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/thetopor
  - title: facebook
    url: https://www.facebook.com/thetoporteam
  - title: twitter
    url: https://twitter.com/topor_io


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Braila,
    - Romania.
email: contact@topor.io


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Alexandru Onea
    position: CEO
    text: Responsible for all the great work done here at Topor. We respect him for that.
    img: me.jpg
    page: /alexandru
    social:
      - title: envelope # use for email address
        url: mailto:alexandru.onea@topor.io
      - title: facebook
        url: https://www.facebook.com/alexandru.n.onea
      - title: github
        url: https://github.com/alexonea
  - name: Răzvan Neacșu
    position: Lead Developer
    text: Also known as Nexus, he is the swiss army knife of the team. His code never breaks.
    img: nexus.jpg
    page: /razvan
    social:
      - title: envelope # use for email address
        url: mailto:razvan.neacsu@topor.io
      - title: facebook
        url: https://www.facebook.com/neacsu.razvan.75
      - title: github
        url: https://github.com/OriginalNexus
  - name: Ionuț Mihalache
    position: Lead Designer
    text: Being creative and open-minded, he inspires the whole team and brings new ideas.
    img: mim.jpg
    page: /ionut
    social:
      - title: envelope # use for email address
        url: mailto:ionut.mihalache@topor.io
      - title: facebook
        url: https://www.facebook.com/ionutzmar
      - title: github
        url: https://github.com/ionutzmar

# Clients information.
clients:
  - name: dacia
    img: dacia.png

# Short text about your company. Shown in footer on every page
about: "Topor is what makes the impossible possible."

# Testimonial content.
testimonial:
    message: "Topor is without doubt the perfect solution for anyone. Reliable, flexible, easy-to-use services, in-depth documentations and excellent support. These guys know their shit."
    author: Frank Lewis
    position: CEO at Brahm Inc.
